# Generated by Django 2.2.3 on 2019-08-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('genres', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('rating_predicted', models.FloatField(default=0.0)),
                ('timestamp', models.FloatField(default=0.0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_recommendation_app.Movie')),
            ],
            options={
                'unique_together': {('userId', 'movie')},
            },
        ),
    ]
